export const PLACE_LIST_REQUEST = 'PLACE_LIST_REQUEST';
export const PLACE_LIST_SUCCESS = 'PLACE_LIST_SUCCESS';
export const PLACE_LIST_FAIL = 'PLACE_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
